import {
  Factory,
  FlaskConical,
  Building2,
  Package,
  ShieldCheck,
  FileText,
  Clock,
  CheckCircle2,
  Award
} from "lucide-react";

export const MTP_CATEGORIES = [
  { id: "all", label: "All M&TP Licences & Permits", icon: Award },
  { id: "manufacturing", label: "Manufacturing", icon: Factory },
  { id: "spirit", label: "Spirit", icon: FlaskConical },
  { id: "bhang", label: "Bhang", icon: Package },
  { id: "drugs", label: "Drugs", icon: Building2 },
  { id: "permits", label: "Permits", icon: FileText }
];

export const MTP_LICENSES_DATA = [
  // 1. M&TP Manufacturing Licences
  {
    id: "L-1 (M&TP)",
    code: "L-1 (M&TP)",
    shortCode: "L1-MTP",
    category: "manufacturing",
    categoryLabel: "M&TP Manufacturing",
    title: "Manufacture under bond",
    fullTitle: "Manufacture of medicinal and toilet preparations containing alcohol, opium, Indian hemp and other narcotic drugs/narcotics under bond",
    description: "Granted for the manufacture of medicinal and toilet preparations containing alcohol and narcotic substances where excise duty is paid upon removal of finished products from the bonded laboratory/warehouse.",
    badge: "Under Bond",
    validity: "1 Year (Renewable for 2026–27)",
    feeFormatted: "₹ 2,00,000 / Year",
    bondFormatted: "₹ 1,00,000 Security Deposit",
    authority: "Excise Commissioner & State Drug Controller, GNCTD",
    eligibility: "Possession of valid Drug Controller Manufacturing License (Form 25/26), bonded warehouse blueprint approval, and flameproof electrical fittings.",
    requiredDocs: [
      "Drug Controller Manufacturing License (Form 25/26)",
      "Approved Bonded Laboratory Plan Blueprint",
      "Fire Safety Clearance / Delhi Fire Service NOC",
      "List of Qualified Chemists & Registered Pharmacists",
      "Excise Bond Undertaking (Form M.T.P. 1/2)"
    ],
    status: "Grant of New Licence / Renewal 2026–27",
    isPermit: false
  },
  {
    id: "L-2 (M&TP)",
    code: "L-2 (M&TP)",
    shortCode: "L2-MTP",
    category: "manufacturing",
    categoryLabel: "M&TP Manufacturing",
    title: "Manufacture outside bond",
    fullTitle: "Manufacture of medicinal and toilet preparations containing alcohol, opium, Indian hemp and other narcotic drugs/narcotics outside bond",
    description: "Granted for manufacture of medicinal and toilet preparations where duty on rectified spirit or alcohol is paid upfront prior to procurement and manufacturing outside bonded premises.",
    badge: "Outside Bond",
    validity: "1 Year (Renewable for 2026–27)",
    feeFormatted: "₹ 1,50,000 / Year",
    bondFormatted: "₹ 50,000 Security Deposit",
    authority: "Excise Commissioner & State Drug Controller, GNCTD",
    eligibility: "Valid Drug Manufacturing Licence, DPCC consent to establish/operate, proof of industrial premises in conforming zone.",
    requiredDocs: [
      "State Drug Controller License",
      "Approved Chemical Assay & Batch Recipe Dossier",
      "Duty Payment Verification Challans",
      "DPCC Environmental Clearance",
      "Factory Directorate Registration"
    ],
    status: "Grant of New Licence / Renewal 2026–27",
    isPermit: false
  },

  // 2. Spirit Licences
  {
    id: "L-4",
    code: "L-4",
    shortCode: "L-4",
    category: "spirit",
    categoryLabel: "Spirit Licences",
    title: "Wholesale vend of Rectified Spirit",
    fullTitle: "Licence for wholesale vend of Rectified Spirit (including 95% v/v industrial/pharmaceutical alcohol)",
    description: "Authorizes the wholesale stocking, procurement from distilleries, and bulk supply of Rectified Spirit to licensed manufacturers, hospitals, laboratories, and educational institutions.",
    badge: "Wholesale Rectified",
    validity: "1 Year (Renewable for 2026–27)",
    feeFormatted: "₹ 1,00,000 / Year",
    bondFormatted: "₹ 50,000",
    authority: "Department of Excise, GNCTD",
    eligibility: "Appropriate storage godowns meeting PESO safety guidelines and spirit containment specifications.",
    requiredDocs: [
      "Storage Godown Blueprint Plan",
      "Explosives / PESO License (where bulk volume exceeds threshold)",
      "Fire Safety Certificate",
      "GSTIN and PAN of Enterprise"
    ],
    status: "Grant of New Licence / Renewal 2026–27",
    isPermit: false
  },
  {
    id: "L-5",
    code: "L-5",
    shortCode: "L-5",
    category: "spirit",
    categoryLabel: "Spirit Licences",
    title: "Wholesale vend of Denatured Spirit",
    fullTitle: "Licence for wholesale vend of Denatured Spirit, including Special Denatured Spirit (SDS)",
    description: "Authorizes wholesale distribution and supply of denatured spirit and special denatured spirit for industrial, paints, chemical processing, and institutional applications.",
    badge: "Wholesale Denatured",
    validity: "1 Year (Renewable for 2026–27)",
    feeFormatted: "₹ 75,000 / Year",
    bondFormatted: "₹ 40,000",
    authority: "Department of Excise, GNCTD",
    eligibility: "Industrial zoning confirmation and compliance with Denatured Spirit Testing Regulations.",
    requiredDocs: [
      "Warehouse Ownership or Lease Agreement",
      "Denaturant Testing Certificate from Govt Lab",
      "Fire NOC & Site Plan"
    ],
    status: "Grant of New Licence / Renewal 2026–27",
    isPermit: false
  },
  {
    id: "L-25",
    code: "L-25",
    shortCode: "L-25",
    category: "spirit",
    categoryLabel: "Spirit Licences",
    title: "Retail vend of Denatured Spirit",
    fullTitle: "Licence for retail vend of Denatured Spirit, including Special Denatured Spirit",
    description: "Authorizes retail sales of denatured alcohol and special denatured spirits directly to verified end-users, artisans, labs, and small-scale processors.",
    badge: "Retail Denatured",
    validity: "1 Year (Renewable for 2026–27)",
    feeFormatted: "₹ 25,000 / Year",
    bondFormatted: "₹ 15,000",
    authority: "Department of Excise, GNCTD",
    eligibility: "Commercial retail shop in conforming commercial/industrial area with fire-extinguisher safety equipment.",
    requiredDocs: [
      "Shop Ownership/Rent Agreement",
      "Municipal Trade License",
      "Identity and Address Proof of Applicant"
    ],
    status: "Grant of New Licence / Renewal 2026–27",
    isPermit: false
  },
  {
    id: "L-26",
    code: "L-26",
    shortCode: "L-26",
    category: "spirit",
    categoryLabel: "Spirit Licences",
    title: "Retail vend of Rectified Spirit",
    fullTitle: "Licence for retail vend of Rectified Spirit",
    description: "Authorizes retail dispensing of pure rectified spirit to medical practitioners, registered dentists, veterinary surgeons, and analytical laboratories.",
    badge: "Retail Rectified",
    validity: "1 Year (Renewable for 2026–27)",
    feeFormatted: "₹ 40,000 / Year",
    bondFormatted: "₹ 20,000",
    authority: "Department of Excise, GNCTD",
    eligibility: "Registered premises with secure spirit dispensing containers and mandatory customer verification ledger.",
    requiredDocs: [
      "Premise Layout & Counter Specification",
      "Verification of Dispensing Chemist",
      "Fire Safety Precautions Declaration"
    ],
    status: "Grant of New Licence / Renewal 2026–27",
    isPermit: false
  },
  {
    id: "L-34",
    code: "L-34",
    shortCode: "L-34",
    category: "spirit",
    categoryLabel: "Spirit Licences",
    title: "Warehouse for storage of Denatured Spirit",
    fullTitle: "Licence for operating a designated warehouse for bulk storage of Denatured Spirit",
    description: "Authorizes maintenance and operation of high-capacity bulk tank farms and storage warehouses for denatured spirit stocks.",
    badge: "Bulk Warehouse",
    validity: "1 Year (Renewable for 2026–27)",
    feeFormatted: "₹ 1,20,000 / Year",
    bondFormatted: "₹ 75,000",
    authority: "Department of Excise, GNCTD",
    eligibility: "Heavy industrial facility with dip-tank calibration certificates and safety earthings.",
    requiredDocs: [
      "Tank Calibration Certificates by Weights & Measures Dept",
      "PESO Petroleum & Explosive Safety Clearance",
      "24x7 CCTV Surveillance Undertaking"
    ],
    status: "Grant of New Licence / Renewal 2026–27",
    isPermit: false
  },
  {
    id: "L-35",
    code: "L-35",
    shortCode: "L-35",
    category: "spirit",
    categoryLabel: "Spirit Licences",
    title: "Warehouse for storage of Rectified Spirit",
    fullTitle: "Licence for operating a designated warehouse for bulk storage of Rectified Spirit",
    description: "Authorizes establishing centralized bonded or non-bonded high-security bulk storage warehouses for rectified spirit.",
    badge: "Bulk Warehouse",
    validity: "1 Year (Renewable for 2026–27)",
    feeFormatted: "₹ 1,50,000 / Year",
    bondFormatted: "₹ 1,00,000",
    authority: "Department of Excise, GNCTD",
    eligibility: "Approved security perimeter, electronic flow-meters, and daily stock ledger inspection readiness.",
    requiredDocs: [
      "Excise Supervisory Check Plan",
      "Storage Vat Calibration Dossier",
      "Security Personnel Roster"
    ],
    status: "Grant of New Licence / Renewal 2026–27",
    isPermit: false
  },
  {
    id: "L-36",
    code: "L-36",
    shortCode: "L-36",
    category: "spirit",
    categoryLabel: "Spirit Licences",
    title: "Medical Practitioner / Chemist Spirituous Sale",
    fullTitle: "Licence for a Registered Medical Practitioner / Chemist / Druggist for sale of intoxicating spirituous preparations",
    description: "Authorizes registered medical practitioners, authorized chemists, and druggists to dispense approved medicinal intoxicating spirituous preparations.",
    badge: "Medical / Chemist",
    validity: "1 Year (Renewable for 2026–27)",
    feeFormatted: "₹ 20,000 / Year",
    bondFormatted: "₹ 10,000",
    authority: "Department of Excise & Drug Controller, GNCTD",
    eligibility: "Medical Council / Pharmacy Council Registration, retail drug sale license (Form 20/21).",
    requiredDocs: [
      "Pharmacy Council Registration Certificate",
      "Drug Store Retail License",
      "Prescription Dispensing Register Undertaking"
    ],
    status: "Grant of New Licence / Renewal 2026–27",
    isPermit: false
  },

  // 3. Bhang
  {
    id: "L-27",
    code: "L-27",
    shortCode: "L-27",
    category: "bhang",
    categoryLabel: "Bhang",
    title: "Retail Vend of Bhang",
    fullTitle: "Licence for the retail vend of Bhang under Delhi Excise & M&TP Branch regulations",
    description: "Authorizes the retail sale and authorized vend of Bhang procured through authorized government quotas in designated municipal locations.",
    badge: "Retail Vend of Bhang",
    validity: "1 Year (Renewable for 2026–27)",
    feeFormatted: "Tender / E-Auction Determined",
    bondFormatted: "₹ 50,000 Minimum",
    authority: "Department of Excise, GNCTD",
    eligibility: "Allotment through official Excise department competitive e-tender/auction process, clean police record.",
    requiredDocs: [
      "Successful E-Auction Allotment Letter",
      "Police Character Verification Certificate",
      "Vend Premise Possession Proof"
    ],
    status: "E-Auction / Grant for 2026–27",
    isPermit: false
  },

  // 4. Manufactured Drug Licences (DD Series)
  {
    id: "DD-2",
    code: "DD-2",
    shortCode: "DD-2",
    category: "drugs",
    categoryLabel: "Manufactured Drugs",
    title: "Import / Transport Pass for Manufactured Drugs",
    fullTitle: "Permit and Pass for import/transport of manufactured drugs other than prepared opium",
    description: "Authorizes cross-border inter-state import or intra-state transit of notified manufactured drugs (under NDPS / Dangerous Drugs rules) into Delhi.",
    badge: "Import / Transport Pass",
    validity: "Consignment Basis (Up to 30 Days)",
    feeFormatted: "₹ 10,000 / Pass",
    bondFormatted: "Covered by Master Drug Bond",
    authority: "Excise Narcotics Division, GNCTD",
    eligibility: "Holding valid DD-9 or DD-10 licence or licensed pharmaceutical manufacturing facility.",
    requiredDocs: [
      "Consignor Export NOC from Origin State",
      "Drug Controller Allotment / Quota Sanction",
      "Vehicle & GPS Transit Plan"
    ],
    status: "Active / Instant Clearance",
    isPermit: true
  },
  {
    id: "DD-3",
    code: "DD-3",
    shortCode: "DD-3",
    category: "drugs",
    categoryLabel: "Manufactured Drugs",
    title: "Export Pass for Manufactured Drugs",
    fullTitle: "Pass for export of manufactured drugs other than prepared opium",
    description: "Statutory transit authorization allowing licensed pharmaceutical entities to dispatch manufactured drugs to authorized purchasers outside the NCT of Delhi.",
    badge: "Export Pass",
    validity: "Consignment Basis",
    feeFormatted: "₹ 10,000 / Pass",
    bondFormatted: "Consignment Verification",
    authority: "Excise Narcotics Division, GNCTD",
    eligibility: "Receipt of valid Import Permit issued by Excise Authority of destination state.",
    requiredDocs: [
      "Destination State Import Permit Copy",
      "Consignee Valid Drug License",
      "Batch Assay Report"
    ],
    status: "Active / Instant Clearance",
    isPermit: true
  },
  {
    id: "DD-4",
    code: "DD-4",
    shortCode: "DD-4",
    category: "drugs",
    categoryLabel: "Manufactured Drugs",
    title: "Transport Pass for Manufactured Drugs",
    fullTitle: "Pass for transport of manufactured drugs other than prepared opium within Delhi NCT",
    description: "Required for intra-city consignment movements of regulated drugs between bonded factory units, central warehouses, and hospital institutions.",
    badge: "Local Transit Pass",
    validity: "7 Days from Date of Issue",
    feeFormatted: "₹ 5,000 / Pass",
    bondFormatted: "Standard",
    authority: "Excise Narcotics Division, GNCTD",
    eligibility: "Registered DD licensee with bonded courier arrangement.",
    requiredDocs: [
      "Requisition Invoice & Waybill",
      "Licensed Receiving Chemist / Hospital Credentials"
    ],
    status: "Active / Digital Pass",
    isPermit: true
  },
  {
    id: "DD-5",
    code: "DD-5",
    shortCode: "DD-5",
    category: "drugs",
    categoryLabel: "Manufactured Drugs",
    title: "Possession & Transport by Approved Practitioner",
    fullTitle: "Licence for possession and transport by an approved practitioner for use in practice",
    description: "Authorizes recognized doctors, palliative care clinicians, and medical specialists to possess and transport controlled alkaloids and manufactured drugs for direct clinical therapy.",
    badge: "Clinical Practitioner",
    validity: "1 Year (Renewable for 2026–27)",
    feeFormatted: "₹ 25,000 / Year",
    bondFormatted: "₹ 10,000",
    authority: "Excise Department & Delhi Medical Council, GNCTD",
    eligibility: "MBBS/MD/Palliative Care Specialist registration with Delhi Medical Council (DMC) or National Medical Commission.",
    requiredDocs: [
      "Medical Council Registration Certificate",
      "Clinic / Hospital Address Proof & Secure Locker Affidavit",
      "Annual Clinical Drug Estimate"
    ],
    status: "Grant of New Licence / Renewal 2026–27",
    isPermit: false
  },
  {
    id: "DD-9",
    code: "DD-9",
    shortCode: "DD-9",
    category: "drugs",
    categoryLabel: "Manufactured Drugs",
    title: "Dealer for Possession & Manufacture",
    fullTitle: "Dealer licence for possession of manufactured drugs for manufacture of medicinal preparations and sale of such preparations",
    description: "Authorizes commercial pharmaceutical manufacturers to procure notified active drug alkaloids, formulate medicinal preparations, and conduct wholesale trade of finished products.",
    badge: "Manufacture & Dealer",
    validity: "1 Year (Renewable for 2026–27)",
    feeFormatted: "₹ 2,00,000 / Year",
    bondFormatted: "₹ 50,000",
    authority: "Excise Narcotics Division & State Drug Controller, GNCTD",
    eligibility: "Approved double-locked concrete strong room, 24x7 CCTV recording with 30-day archival, and approved chemical analyst.",
    requiredDocs: [
      "State Drug Controller Manufacturing License (Form 25)",
      "Double-Lock Vault Security Blueprint & Affidavit",
      "Approved Chemist Appointment Affidavit",
      "PESO and Fire Safety Clearance"
    ],
    status: "Grant of New Licence / Renewal 2026–27",
    isPermit: false
  },
  {
    id: "DD-10",
    code: "DD-10",
    shortCode: "DD-10",
    category: "drugs",
    categoryLabel: "Manufactured Drugs",
    title: "Wholesale Possession & Sale (Otherwise than on Prescription)",
    fullTitle: "Dealer licence for possession and sale of manufactured drugs/preparations otherwise than on prescription",
    description: "Authorizes wholesale stocking, distribution, and inter-institutional supply of manufactured drugs to certified dispensaries, hospitals, and licensed pharmacies.",
    badge: "Wholesale Dealer",
    validity: "1 Year (Renewable for 2026–27)",
    feeFormatted: "₹ 1,50,000 / Year",
    bondFormatted: "₹ 40,000",
    authority: "Excise Narcotics Division, GNCTD",
    eligibility: "Holding wholesale drug license (Form 20B/21B), secure narcotics safe custody, and computerized stock reconciliation software.",
    requiredDocs: [
      "Wholesale Drug License (Form 20B/21B)",
      "Strong Room / Vault Audit Certificate",
      "Authorized Signatory & Pharmacist KYC"
    ],
    status: "Grant of New Licence / Renewal 2026–27",
    isPermit: false
  },
  {
    id: "DD-11",
    code: "DD-11",
    shortCode: "DD-11",
    category: "drugs",
    categoryLabel: "Manufactured Drugs",
    title: "Chemist Licence for Sale on Prescription",
    fullTitle: "Chemist licence for sale on prescription for medical purposes under Dangerous Drugs rules",
    description: "Authorizes retail pharmacies and hospital dispensaries to store and dispense manufactured drugs and narcotics strictly against authenticated medical prescriptions.",
    badge: "Dispensing Chemist",
    validity: "1 Year (Renewable for 2026–27)",
    feeFormatted: "₹ 50,000 / Year",
    bondFormatted: "₹ 20,000",
    authority: "Excise Narcotics Division & Drug Controller, GNCTD",
    eligibility: "Active retail pharmacy (Form 20/21) with dedicated locked narcotic safe and physical prescription register.",
    requiredDocs: [
      "Pharmacy Retail License (Form 20/21)",
      "Registered Pharmacist Registration Certificate",
      "Narcotics Locker Security Declaration"
    ],
    status: "Grant of New Licence / Renewal 2026–27",
    isPermit: false
  },

  // 5. M&TP Permits (P Series)
  {
    id: "P-1",
    code: "P-1",
    shortCode: "P-1",
    category: "permits",
    categoryLabel: "M&TP Permits",
    title: "Import Permit for Spirits",
    fullTitle: "Import of Rectified Spirit, Denatured Spirit and Special Denatured Spirit into NCT of Delhi",
    description: "Authorizes bringing Rectified Spirit (RS), Denatured Spirit (DS), or Special Denatured Spirit (SDS) from distilleries located outside Delhi into the capital territory.",
    badge: "Bulk Spirit Import",
    validity: "Consignment Transit Period (30 Days)",
    feeFormatted: "₹ 15,000 / Consignment",
    bondFormatted: "Transit Indemnity Bond",
    authority: "M&TP Branch, Excise Dept, GNCTD",
    eligibility: "Holder of valid manufacturing or storage license (L-1, L-2, L-4, L-5, L-34, L-35).",
    requiredDocs: [
      "Distillery Allotment Sanction Letter",
      "Excise Verification Certificate of Supplying State",
      "Transit Tanker / Container Calibration Details"
    ],
    status: "Online Permit Issuance",
    isPermit: true
  },
  {
    id: "P-2",
    code: "P-2",
    shortCode: "P-2",
    category: "permits",
    categoryLabel: "M&TP Permits",
    title: "Possession of Denatured Spirit (5L to 10L)",
    fullTitle: "Permit for possession of Denatured Spirit exceeding 5 litres up to 10 litres",
    description: "Permits institutions, small workshops, testing labs, and dental clinics to legally possess denatured spirit between 5 to 10 litres.",
    badge: "Possession (5L–10L)",
    validity: "1 Year",
    feeFormatted: "₹ 2,500 / Year",
    bondFormatted: "Self-Declaration",
    authority: "M&TP Branch, Excise Dept, GNCTD",
    eligibility: "Legitimate institutional, scientific, or trade justification.",
    requiredDocs: [
      "Institutional Proof / Trade Registration",
      "Storage Safety Statement"
    ],
    status: "Instant Online Grant",
    isPermit: true
  },
  {
    id: "P-3",
    code: "P-3",
    shortCode: "P-3",
    category: "permits",
    categoryLabel: "M&TP Permits",
    title: "Possession of Denatured Spirit (>10L)",
    fullTitle: "Permit for possession of Denatured Spirit exceeding 10 litres",
    description: "Mandatory permit for entities requiring possession of denatured spirit in volumes greater than 10 litres for commercial or analytical use.",
    badge: "Possession (>10L)",
    validity: "1 Year",
    feeFormatted: "₹ 10,000 / Year",
    bondFormatted: "₹ 10,000",
    authority: "M&TP Branch, Excise Dept, GNCTD",
    eligibility: "Verified industrial, commercial, or laboratory user with approved safety storage drums.",
    requiredDocs: [
      "Technical Justification of Annual Requirement",
      "Storage Room Safety Inspection Report",
      "GST Registration Certificate"
    ],
    status: "Fast-Track Approval",
    isPermit: true
  },
  {
    id: "P-4",
    code: "P-4",
    shortCode: "P-4",
    category: "permits",
    categoryLabel: "M&TP Permits",
    title: "Special Denatured Spirit in Bulk Quantity",
    fullTitle: "Permit for possession of Special Denatured Spirit (SDS) in bulk quantity",
    description: "Permits major industrial processing units, polymer, or chemical synthesis plants to hold bulk SDS stocks.",
    badge: "SDS Bulk Possession",
    validity: "1 Year (Renewable)",
    feeFormatted: "₹ 50,000 / Year",
    bondFormatted: "₹ 50,000",
    authority: "M&TP Branch, Excise Dept, GNCTD",
    eligibility: "Industrial manufacturing unit with dedicated bulk tanks and automated consumption logging.",
    requiredDocs: [
      "Industrial Plant Registration",
      "DPCC Environmental Consent",
      "Bulk Tank Storage Certificate"
    ],
    status: "Technical Scrutiny Track",
    isPermit: true
  },
  {
    id: "P-5",
    code: "P-5",
    shortCode: "P-5",
    category: "permits",
    categoryLabel: "M&TP Permits",
    title: "Rectified Spirit by Educational Institutions",
    fullTitle: "Permit for possession of Rectified Spirit by educational institutions, universities & research labs",
    description: "Concessional statutory permit enabling accredited colleges, science faculties, and medical research institutes to keep rectified spirit for laboratory experiments.",
    badge: "Educational / Research",
    validity: "1 Academic Year",
    feeFormatted: "₹ 5,000 / Year",
    bondFormatted: "Institutional Guarantee",
    authority: "M&TP Branch, Excise Dept, GNCTD",
    eligibility: "UGC / AICTE / Medical Council recognized university, college, or school department.",
    requiredDocs: [
      "Institution Accreditation Letter",
      "Authorization Letter from Registrar / Principal / Dean",
      "Head of Chemistry / Biology Dept Declaration"
    ],
    status: "Education Fast-Track",
    isPermit: true
  },
  {
    id: "P-6",
    code: "P-6",
    shortCode: "P-6",
    category: "permits",
    categoryLabel: "M&TP Permits",
    title: "Special Denatured Spirit by Industrial Manufacturers",
    fullTitle: "Permit for possession of Special Denatured Spirit by industrial manufacturers",
    description: "Issued to licensed manufacturers utilizing special denaturants (e.g. for lacquer, pharmaceuticals, sanitizers, or specialized reagents).",
    badge: "Industrial SDS",
    validity: "1 Year (Renewable)",
    feeFormatted: "₹ 40,000 / Year",
    bondFormatted: "₹ 25,000",
    authority: "M&TP Branch, Excise Dept, GNCTD",
    eligibility: "Approved manufacturing formula indicating necessity of approved special denaturant.",
    requiredDocs: [
      "Formulation Spec Sheet Approved by Chemical Examiner",
      "Factory License",
      "Pollution Control Clearance"
    ],
    status: "Active / Online Processing",
    isPermit: true
  },
  {
    id: "P-7",
    code: "P-7",
    shortCode: "P-7",
    category: "permits",
    categoryLabel: "M&TP Permits",
    title: "Possession of Intoxicating Spirituous Preparations",
    fullTitle: "Permit for possession of Intoxicating Spirituous Preparations (ISP)",
    description: "Governs possession of high alcoholic strength medicinal elixirs, tinctures, and liquid preparations deemed intoxicating under excise rules.",
    badge: "ISP Possession",
    validity: "1 Year",
    feeFormatted: "₹ 20,000 / Year",
    bondFormatted: "₹ 15,000",
    authority: "M&TP Branch, Excise Dept, GNCTD",
    eligibility: "Licensed wholesale distributor or medical facility.",
    requiredDocs: [
      "Drug Controller License",
      "List of Specified Tinctures / Preparations",
      "Secure Stock Room Proof"
    ],
    status: "Active / Online Processing",
    isPermit: true
  },
  {
    id: "P-8",
    code: "P-8",
    shortCode: "P-8",
    category: "permits",
    categoryLabel: "M&TP Permits",
    title: "Import or Transport of ISP",
    fullTitle: "Permit for import or transport of Intoxicating Spirituous Preparations into or within Delhi",
    description: "Mandatory consignment permit for shipping or receiving medicinal tinctures and spirituous preparations with potential for intoxicating use.",
    badge: "ISP Transit",
    validity: "Consignment Basis",
    feeFormatted: "₹ 5,000 / Permit",
    bondFormatted: "Standard",
    authority: "M&TP Branch, Excise Dept, GNCTD",
    eligibility: "Holder of P-7 permit or licensed pharmaceutical distributor.",
    requiredDocs: [
      "P-7 Master Permit Copy",
      "Supplier Invoice and Chemical Test Assay",
      "Transit Route & Carrier Details"
    ],
    status: "Online Permit Issuance",
    isPermit: true
  },
  {
    id: "P-12",
    code: "P-12",
    shortCode: "P-12",
    category: "permits",
    categoryLabel: "M&TP Permits",
    title: "Import, Export or Transport of Bhang",
    fullTitle: "Permit for import, export or transport of Bhang under M&TP Branch statutory quotas",
    description: "Authorizes the cross-border transit or intra-Delhi transfer of statutory Bhang consignments by licensed vends or authorized processors.",
    badge: "Bhang Transit",
    validity: "Consignment Basis (15 Days)",
    feeFormatted: "₹ 10,000 / Consignment",
    bondFormatted: "Security Deposit",
    authority: "M&TP Branch, Excise Dept, GNCTD",
    eligibility: "Holder of valid L-27 license or government authorized processor.",
    requiredDocs: [
      "L-27 Retail Vend License Copy",
      "Consignment Origin Permit",
      "Sealed Transit Certificate"
    ],
    status: "Statutory Clearance Track",
    isPermit: true
  }
];
