export const createApplicant = () => ({
  applicantName: "",
  CompanyName: "",
  dob: "",
  FatherHusbandName: "",
  Occupation: "",

  PresentAddress: "",
  PermanentAddress: "",
  address: "",
addressLine1: "",
addressLine2: "",
  name: "",
  StateUT: "",
  district: "",
  WarehouseSubDivision: "",
  WarehousePoliceStation: "",
  PIN: "",
  ownerType: "",
  EmailId: "",
  MobileNo: "",
  contact: "",
  LandLine: "",
  fax: "",
email: "",
  panNo: "",
  size: "",
  licensePremise: "",
landline: "",
  registrationNo: "",
  registrationDate: "",
  expirationDate: "",
OwnerType: "",
  ArchitectRegistrationNo: "",
  ArchitectRegistrationNoValidUpto: "",

  SuperAreaofLicensePremise: "",
  CarpetAreaofLicensePremise: "",
  DistanceofDistillery: "",
  hoursOfSale: "",
CatCode: "",
  constitutionType: "",
  cinNo: "",

  registration: "",
  registrationDateCompany: "",

  directors: [
    {
      name: "",
      share: "",
      panNo: "",
      exciseNominee: "",
      panFile: null,
      addressFile: null,
      dinNo: "",
    },
  ],
});
