export const createApplicant = () => ({
  applicantName: "",
  CompanyName: "",
  dob: "",
  FatherHusbandName: "",
  Occupation: "",

  PresentAddress: "",
  PermanentAddress: "",
  address: "",
addressLine1: "",
addressLine2: "",
  name: "",
  StateUT: "",
  district: "",
  WarehouseSubDivision: "",
  WarehousePoliceStation: "",
  PIN: "",
  ownerType: "",
  EmailId: "",
  MobileNo: "",
  contact: "",
  LandLine: "",
  fax: "",
email: "",
  panNo: "",
  size: "",
  licensePremise: "",
landline: "",
  RegistrationNo: "",
  RegDate: "",
  expirationDate: "",
OwnerType: "",
  ArchitectRegistrationNo: "",
  ArchitectRegistrationNoValidUpto: "",

  SuperAreaofLicensePremise: "",
  CarpetAreaofLicensePremise: "",
  DistanceofDistillery: "",
  hoursOfSale: "",
CatCode: "",
  ConstitutionType: "",
  CINNO: "",

  registration: "",
  registrationDateCompany: "",

  directors: [
    {
      PName: "",
      PPerShare: "",
      PPanNo: "",
      PExciseNominee: "",
      DocSlNo:"",
      PhotoURLPanNo: null,
      PhotoURLAddressProof: null,
      DINNo: "",
    },
  ],
});
