// <auto-generated />
using DOTNETAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DOTNETAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251209074833_AddStateIdToDistrict")]
    partial class AddStateIdToDistrict
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DOTNETAPI.Models.MstDistrict", b =>
                {
                    b.Property<int>("DistCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DistCode"));

                    b.Property<string>("DistName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StateCode")
                        .HasColumnType("int");

                    b.HasKey("DistCode");

                    b.ToTable("MstDistrict");
                });

            modelBuilder.Entity("DOTNETAPI.Models.Licensee_Category", b =>
                {
                    b.Property<string>("licensee_cat_code")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("licensee_cat_code");

                    b.Property<string>("licensee_cat_desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("licensee_cat_desc");

                    b.HasKey("licensee_cat_code");

                    b.ToTable("Licensee_Category");
                });

            modelBuilder.Entity("DOTNETAPI.Models.MstState", b =>
                {
                    b.Property<int>("StateCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StateCode"));

                    b.Property<string>("EntType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StateCode");

                    b.ToTable("MstState");
                });
#pragma warning restore 612, 618
        }
    }
}
