// <auto-generated />
using System;
using DOTNETAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DOTNETAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251217064025_AddApplicationLicenseDocumentMasters")]
    partial class AddApplicationLicenseDocumentMasters
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DOTNETAPI.Models.ApplicationLicenseDocumentMaster", b =>
                {
                    b.Property<int>("DocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Doc_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocId"));

                    b.Property<string>("DeleteStatus")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("Delete_Status");

                    b.Property<string>("DocDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Doc_Desc");

                    b.Property<string>("DocStatus")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("Doc_Status");

                    b.Property<bool?>("IsValid")
                        .HasColumnType("bit")
                        .HasColumnName("IsValid");

                    b.HasKey("DocId");

                    b.ToTable("Application_License_Document_Master");
                });

            modelBuilder.Entity("DOTNETAPI.Models.Licensee_Category", b =>
                {
                    b.Property<string>("licensee_cat_code")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("licensee_cat_code");

                    b.Property<string>("licensee_cat_desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("licensee_cat_desc");

                    b.HasKey("licensee_cat_code");

                    b.ToTable("Licensee_Category");
                });

            modelBuilder.Entity("DOTNETAPI.Models.MstDistrict", b =>
                {
                    b.Property<string>("DistCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DistName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EntType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("DistCode");

                    b.HasIndex("StateCode");

                    b.ToTable("MstDistrict");
                });

            modelBuilder.Entity("DOTNETAPI.Models.MstState", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StateId"));

                    b.Property<string>("EntType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StateId");

                    b.HasAlternateKey("StateCode")
                        .HasName("AK_MstState_StateCode");

                    b.ToTable("MstState");
                });

            modelBuilder.Entity("DOTNETAPI.Models.MstDistrict", b =>
                {
                    b.HasOne("DOTNETAPI.Models.MstState", "State")
                        .WithMany("Districts")
                        .HasForeignKey("StateCode")
                        .HasPrincipalKey("StateCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("DOTNETAPI.Models.MstState", b =>
                {
                    b.Navigation("Districts");
                });
#pragma warning restore 612, 618
        }
    }
}
